### ISSUE TITLE
属性 wheelVelocityUnits 获取错误

### ISSUE THREAD

**Issue by zhaowenliang** [JustinRoom/WheelViewDemo#11]
[WheelView](https://github.com/JustinRoom/WheelViewDemo/blob/master/wheelLibrary/src/main/java/jsc/kit/wheel/base/WheelView.java)

其中获取 wheelVelocityUnits  属性使用了wheelRotationX 属性值。

```Java
wheelRotationX = a.getFloat(R.styleable.WheelView_wheelRotationX, DEFAULT_ROTATION_X);
velocityUnits = a.getInteger(R.styleable.WheelView_wheelRotationX, DEFAULT_VELOCITY_UNITS);
```

**Comment by JustinRoom** [comment]
好的。我修复下
