### ISSUE TITLE
月份显示有问题

### ISSUE THREAD

**Issue by sanyuanzhang** [JustinRoom/WheelViewDemo#5]
第一次打开时间选择器显示的不是当月的月份，而是显示的上月的月份。关闭弹框再打开显示正常，再关闭再打开显示异常。

**Comment by Keeeeecz** [comment]
> 第一次打开时间选择器显示的不是当月的月份，而是显示的上月的月份。关闭弹框再打开显示正常，再关闭再打开显示异常。

原因好像是initSelectedDate()这个方法里面的月份没有+1，但是由于代码写的比较死，所以不能通过Override来解决。
不过你可以在显示dialog的时候调用两次updateSelectedDate()，因为在刷新滚动的过程中会自动校正先前的错误

**Comment by df13954** [comment]
具体代码在
DateTimeWheelDialog类
initSelectedDate方法
index = findSelectedIndexByValue(monthItems, month +1);
这里加1就显示正常。 选择返回的也是正常。

**Comment by JustinRoom** [comment]
已修复。
