### ISSUE TITLE
一个很普通的bug。2月有30，和31

### ISSUE THREAD

**Issue by df13954** [JustinRoom/WheelViewDemo#7]
时间选择，2月的天，发现有30，31。这个不打算修复吗

**Comment by df13954** [comment]
这个今天发现了触发的逻辑：》
找一个年份，选择一个月份有31号的，比如2020，3月，选择到31日这天。
立马切换年份，切换月份到2月。这个时候，滚动到最后就可以看到日哪里有31天了。
切换需要快点，才能触发这个bug。

**Comment by JustinRoom** [comment]
已修复：当切换月份时，没有考虑Calendar.DAY_OF_MONTH。比如说选中3月31日，切换到2月份时，只设置了Calendar.MONTH的值，它的Calendar.DAY_OF_MONTH还是31，这时候它实际上变成了3月3日。

**Comment by df13954** [comment]
> 已修复：当切换月份时，没有考虑Calendar.DAY_OF_MONTH。比如说选中3月31日，切换到2月份时，只设置了Calendar.MONTH的值，它的Calendar.DAY_OF_MONTH还是31，这时候它实际上变成了3月3日。

哈哈没想到还能看到回复，我已经从上家跑路了

**Comment by JustinRoom** [comment]
> 

恭祝步步高升！٩(๑❛ᴗ❛๑)۶
